[pytest]
testpaths = tests
pythonpath = .
python_files = test_*.py
addopts = -v
filterwarnings =
    ignore:The set_bad function will be deprecated.*:PendingDeprecationWarning:shap\.plots\.colors\._colors
    ignore:The set_over function will be deprecated.*:PendingDeprecationWarning:shap\.plots\.colors\._colors
    ignore:The set_under function will be deprecated.*:PendingDeprecationWarning:shap\.plots\.colors\._colors